--------------------------------------------------------
--  File created - Wednesday-March-18-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEATER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TEATER" 
   (	"NOMOR_TEATER" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KURSI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."KURSI" 
   (	"NOMOR_KURSI" VARCHAR2(10 BYTE), 
	"NOMOR_TEATER" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TEATER
SET DEFINE OFF;
Insert into SYSTEM.TEATER (NOMOR_TEATER) values ('Teater 1');
Insert into SYSTEM.TEATER (NOMOR_TEATER) values ('Teater 5');
REM INSERTING into SYSTEM.KURSI
SET DEFINE OFF;
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('A1','Teater 1');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('A2','Teater 1');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('A3','Teater 1');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('B1','Teater 1');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('B2','Teater 1');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('E3','Teater 5');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('E4','Teater 5');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('E7','Teater 5');
Insert into SYSTEM.KURSI (NOMOR_KURSI,NOMOR_TEATER) values ('E8','Teater 5');
--------------------------------------------------------
--  DDL for Index SYS_C008384
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008384" ON "SYSTEM"."TEATER" ("NOMOR_TEATER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C008385
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008385" ON "SYSTEM"."KURSI" ("NOMOR_KURSI", "NOMOR_TEATER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEATER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TEATER" ADD PRIMARY KEY ("NOMOR_TEATER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KURSI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."KURSI" ADD PRIMARY KEY ("NOMOR_KURSI", "NOMOR_TEATER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KURSI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."KURSI" ADD FOREIGN KEY ("NOMOR_TEATER")
	  REFERENCES "SYSTEM"."TEATER" ("NOMOR_TEATER") ENABLE;
